name: Test error 5th repo - First workflow

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  setup-go:
    runs-on: ubuntu-latest
    steps:
      - name: Setup tar default options
        shell: bash
        run: echo "TAR_OPTIONS=--skip-old-files" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true

      - name: go version
        run: go version

      - name: Run app
        run: go run ./main.go
