name: Test error 5th repo - First workflow
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  setup-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: false

      # - name: Set permissions 
      #   run: sudo chmod -R 777 /home/runner/go/pkg/mod

      # - name: Pre-clean cache directory
      #   run: |
      #     rm -rf /home/runner/go/pkg/mod
      #     rm -rf /home/runner/.cache/go-build
      - name: go version
        run: go version
      - name: Run app
        run: go run ./main.go
