    - name: Cache Go Modules
        id: cache-go-mod
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
          # Exclude the toolchain directory from caching
          exclude: |
            ~/go/pkg/mod/golang.org/toolchain
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-mod-

      - name: Cache Go Build
        id: cache-go-build
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/*.go') }}
          restore-keys: |
            ${{ runner.os }}-go-build-

      - name: Setup Toolchain
        run: |
          go install golang.org/toolchain@latest
